Спринт 15
Evgen1aGerasimenko/java-shareit pull request #2
Opened 2024-09-20 20:26 UTC by Evgen1aGerasimenko

2024-09-21 05:33 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-09-21 05:33 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    BookingDto postBooking(Long userId, CreateBookingDto createBookingDto);
createBooking

2024-09-21 05:33 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        booking.setBooker(UserMapper.toUser(userDto));
давайте это уберем в BookingMapper.toBooking
```
booking.setBooker(UserMapper.toUser(userDto));
booking.setItem(ItemMapper.toItem(itemDto));
booking.setStatus(Status.WAITING);
```

2024-09-21 05:33 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new BadRequestException("Вещь не доступна для бронирования");
тут наверно ForbiddenException больше подходит

2024-09-21 05:33 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return BookingMapper.toBookingDto(bookingRepository.getById(bookingId));
bookingRepository.getById(bookingId) вынесите в переменную внуьри метода

2024-09-21 05:33 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        userService.getUserById(userId);
создайте приватный метод checkIfUserExists() и уберите эту логику туда

2024-09-21 05:33 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        userService.getUserById(userId);
создайте приватный метод checkIfUserExists() и уберите эту логику туда

2024-09-21 05:33 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    ItemDto postItem(Long userId, ItemDto item);
createItem

2024-09-21 05:33 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +
почему пустой? где то используется? если нет, то удалите

2024-09-21 08:37 UTC, Evgen1aGerasimenko commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new BadRequestException("Вещь не доступна для бронирования");
тест ожидает ошибку с кодом 400

2024-09-22 08:32 UTC, ErkinKasymaliev approved these changes
привет, работа принята!

2024-09-23 21:24 UTC, merged